// import type { Metadata } from "next";
// import { Geist, Geist_Mono, Inter } from "next/font/google";
// // import "./globals3.css";
// // import "./components/style/index.css";
// import "../globals3.css";
// import "../components/style/index.css";
// import clsx from "clsx";
// import FireFliesBackground from "../components/FireFliesBackground";
// import LanguageToggleBtn from "../components/LanguageToggleBtn";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// const inter = Inter({
//   subsets: ["latin"],
//   variable: "--font-inter",
// })

// interface RootLayoutProps {
//   children: React.ReactNode
// }


// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={clsx(inter.variable, "bg-background text-foreground font-inter")}>
//         {children}
//         <FireFliesBackground />
//         <LanguageToggleBtn />
//       </body>
//     </html>
//   );
// }




















// // app/[locale]/layout.tsx
// import { NextIntlClientProvider } from 'next-intl';
// import { getMessages, getTranslations } from 'next-intl/server';
// import { notFound } from 'next/navigation';
// import { routing } from '../i18n/routing';
// import { Inter } from 'next/font/google';
// import '../globals3.css';
// import '../components/style/index.css';
// import clsx from 'clsx';
// import FireFliesBackground from '../components/FireFliesBackground';

// const inter = Inter({
//   subsets: ["latin"],
//   variable: "--font-inter",
// });

// export async function generateMetadata({ params: { locale } }: { params: { locale: string } }) {
//   const t = await getTranslations({ locale, namespace: 'Metadata' });

//   return {
//     title: t('title'),
//     description: t('description'),
//   };
// }

// export default async function LocaleLayout({
//   children,
//   params: { locale }
// }: {
//   children: React.ReactNode;
//   params: { locale: string };
// }) {
//   if (!routing.locales.includes(locale as any)) {
//     notFound();
//   }

//   const messages = await getMessages();

//   return (
//     <html lang={locale}>
//       <body className={clsx(inter.variable, "bg-background text-foreground font-inter relative")}>
//         <div id="my-modal" />
//         <NextIntlClientProvider messages={messages} locale={locale}>
//           {children}
//           <FireFliesBackground />
//         </NextIntlClientProvider>
//       </body>
//     </html>
//   );
// }










// // app/[locale]/layout.tsx
// import { NextIntlClientProvider } from 'next-intl';
// import { getMessages, getTranslations } from 'next-intl/server';
// import { notFound } from 'next/navigation';
// import { routing } from '../i18n/routing';
// import { Inter } from 'next/font/google';
// import '../globals3.css';
// import '../components/style/index.css';
// import clsx from 'clsx';
// import FireFliesBackground from '../components/FireFliesBackground';
// import LanguageToggleBtn from '../components/LanguageToggleBtn';

// const inter = Inter({
//   subsets: ["latin"],
//   variable: "--font-inter",
// });

// // Correction: params doit être awaited
// export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }) {
//   const { locale } = await params;
//   const t = await getTranslations({ locale, namespace: 'Metadata' });

//   return {
//     title: t('title'),
//     description: t('description'),
//   };
// }

// export default async function LocaleLayout({
//   children,
//   params,
// }: {
//   children: React.ReactNode;
//   params: Promise<{ locale: string }>;
// }) {
//   // Await params avant de destructurer
//   const { locale } = await params;

//   if (!routing.locales.includes(locale as any)) {
//     notFound();
//   }

//   const messages = await getMessages();

//   return (
//     <html lang={locale}>
//       <body className={clsx(inter.variable, "bg-background text-foreground font-inter relative")}>
//         <div id="my-modal" />
//         <NextIntlClientProvider messages={messages} locale={locale}>
//           <LanguageToggleBtn />
//           {children}
//           <FireFliesBackground />
//         </NextIntlClientProvider>
//       </body>
//     </html>
//   );
// }


















// // app/[locale]/layout.tsx
// import { NextIntlClientProvider } from 'next-intl';
// import { notFound } from 'next/navigation';
// import { routing } from '../i18n/routing';
// import { Inter } from 'next/font/google';
// import '../globals3.css';
// import '../components/style/index.css';
// import clsx from 'clsx';
// import FireFliesBackground from '../components/FireFliesBackground';
// import LanguageToggleBtn from '../components/LanguageToggleBtn';

// const inter = Inter({
//   subsets: ["latin"],
//   variable: "--font-inter",
// });

// // Import direct des messages
// async function getMessages(locale: string) {
//   try {
//     return (await import(`../../messages/${locale}.json`)).default;
//   } catch (error) {
//     notFound();
//   }
// }

// export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }) {
//   const { locale } = await params;

//   const messages = await getMessages(locale);

//   return {
//     title: messages.Metadata?.title || 'Portfolio',
//     description: messages.Metadata?.description || '',
//   };
// }

// export default async function LocaleLayout({
//   children,
//   params,
// }: {
//   children: React.ReactNode;
//   params: Promise<{ locale: string }>;
// }) {
//   const { locale } = await params;

//   if (!routing.locales.includes(locale as any)) {
//     notFound();
//   }

//   const messages = await getMessages(locale);

//   return (
//     <html lang={locale}>
//       <body className={clsx(inter.variable, "bg-background text-foreground font-inter relative")}>
//         <div id="my-modal" />
//         <NextIntlClientProvider messages={messages} locale={locale}>
//           <LanguageToggleBtn />
//           {children}
//           <FireFliesBackground />
//         </NextIntlClientProvider>
//       </body>
//     </html>
//   );
// }




























// app/[locale]/layout.tsx
import { NextIntlClientProvider } from 'next-intl';
import { getMessages, getTranslations } from 'next-intl/server';
import { notFound } from 'next/navigation';
// import { routing } from '../../i18n/routing';
import { Inter } from 'next/font/google';
import '../globals3.css';
import '../components/style/index.css';
import clsx from 'clsx';
import FireFliesBackground from '../components/FireFliesBackground';
import LanguageToggleBtn from '../components/LanguageToggleBtn';
import { routing } from '../../i18n/routing'; 

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  const t = await getTranslations({ locale, namespace: 'Metadata' });

  return {
    title: t('title'),
    description: t('description'),
  };
}

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={clsx(inter.variable, "bg-background text-foreground font-inter relative")}>
        <div id="my-modal" />
        <NextIntlClientProvider messages={messages} locale={locale}>
          <LanguageToggleBtn />
          {children}
          <FireFliesBackground />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
